# Discrete Network (Basit Örnekleri)

In [9]:
import numpy as np
import theano
import lasagne
import theano.tensor as T
from DiscreteLayer import DiscreteLayer
from lasagne.layers import InputLayer, DenseLayer

In [26]:
# Bins
bins_choose = np.linspace(-3, 3, 100)
input_size = 3
t_size = input_size*6
bins = np.tile(bins_choose, t_size).reshape((t_size, -1))
    
network = InputLayer(shape=(input_size, 6))
#network = DenseLayer(network, num_units=6) # Uncomment this line to see the error
network = DiscreteLayer(network, bins=bins)

In [27]:
# Trainer Function and Variable Holders
X = T.matrix('inputs', dtype=theano.config.floatX)
Y = T.matrix('targets', dtype=theano.config.floatX)

params = lasagne.layers.get_all_params(network, trainable=True)
output = lasagne.layers.get_output(network, X, deterministic=False)
cost = T.mean(lasagne.objectives.squared_error(output, Y))
updates = lasagne.updates.nesterov_momentum(cost, params, learning_rate=0.01, momentum=0.9)

train_func = theano.function([X, Y], [cost, output], updates=updates, allow_input_downcast=True)
eval_func = theano.function([X], [output], allow_input_downcast=True)

In [31]:
inp = np.random.rand(input_size, 6)
out = eval_func(inp)
print "---Inputs---\n"
print np.array_str(inp)
print "\n---Discreted Outputs---\n"
print np.array_str(out[0])

---Inputs---

[[ 0.6315526   0.23863341  0.96095111  0.66420804  0.85523071  0.36330735]
 [ 0.1099402   0.40556576  0.05734222  0.7279611   0.4082129   0.53728607]
 [ 0.726888    0.38444794  0.04176623  0.42993391  0.08866254  0.95197624]]

---Discreted Outputs---

[[ 0.63636363  0.21212122  0.93939394  0.63636363  0.87878788  0.33333334]
 [ 0.09090909  0.39393941  0.03030303  0.75757575  0.39393941  0.5151515 ]
 [ 0.69696969  0.39393941  0.03030303  0.45454547  0.09090909  0.93939394]]


In [20]:
# Print Network Graph
theano.printing.pydotprint(eval_func, outfile="Simple_Network.png", var_with_name_simple=True)
theano.printing.pydotprint(train_func, outfile="Simple_Network_train.png", var_with_name_simple=True)  

The output file is available at Simple_Network.png
The output file is available at Simple_Network_train.png
